--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2022. 12. 16. 0:55:08
-- Server version: 10.4.25
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE gamebase;

--
-- Drop table `games`
--
DROP TABLE IF EXISTS games;

--
-- Set default database
--
USE gamebase;

--
-- Create table `games`
--
CREATE TABLE games (
  id int(11) NOT NULL AUTO_INCREMENT,
  jateknev varchar(255) NOT NULL,
  kategoria varchar(255) NOT NULL,
  kiadas_eve year(4) NOT NULL,
  platform varchar(255) NOT NULL,
  kiado varchar(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 13,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

-- 
-- Dumping data for table games
--
INSERT INTO games VALUES
(2, 'Team Fortress 2', 'FPS', 2007, 'Windows', 'Valve'),
(3, 'League of Legends', 'MOBA', 2009, 'Windows', 'Riot Games'),
(4, 'Rocket League', 'Sports', 2015, 'Windows', 'Psyonix');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;