version: '3.4'

services:
  nestjsdemo:
    image: postgres:13
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs_demo
    ports:
      - 5434:5432
